travis:
  secure:
    BINSTAR_TOKEN: PYjteZhpARRWERmEVDAFu8m79aSG5jZ6iqLV1KT2RARXMle4I+WCuLlVi/ympt982KE/d78kg6saq2VmOG2zFuEaTphnUWbpvhGlx0LkQh8mfi/HqofA3vhByfv35F2q8thEnl8xZ1Tf5dUX2dBBKNGSe2AY/3iVr8RtjTutP0/TM3gD0/llfBDHOsT+jTMZNemtmii2sP+kbuRKSZW0rOmdW3Jq4bHluOV0d6HSJUvHGXc5iH9wT0kYHbAIlMW2HdeSGNIFKzY32Mw0HAMrk9F1WhRlR2jo/OGnvvURif9rOyOEQYVVXb5jShqjCGtSPM/FEhCT0MJWJt5yXFkRXGob/iBCCJVQI7birlG8p5Uuked+NdiivQXVZ6mwliAxbihP6IkJImexFS80nFSLz6PFCcvGmNhYhPdASAjLiwByTjVYXUMYCjdb0r3MzmFn6xam9l+e0lGQJIIPS25bcQf0GlxMdwIZKA6L+tFisrELV5apeq1lxsljSq0PYoLD1EaClMAcE5yJV4FDCJwxsp9EWGNPTRQsVpb1r8tC+uTOcNfZZ7JBDVxORQdkOD/bB5bVVVZ7qR9Ptfx7SHf1ZyqIFmWFRFsDH3O28tfQ6WIIUk78SUcRVOQ4C9u/IcNgCuoCzm+yr7yyyel+AjCOxAFOKHGoz4mlN5dm0SyacQI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
